### ISSUE TITLE
Failure to find Failure to find net.onebean:net.onebean.spring.boot:pom:1.1.0.3.RELEASE:1.1.0.3.RELEASE

### ISSUE THREAD

**Issue by gengxiang** [0nebean/net.onebean.kepler#1]
where can i find out net.onebean:net.onebean.spring.boot:pom:1.1.0.3.RELEASE

**Comment by 0nebean** [comment]
when the domain approved,i'll upload pom file to the maven repository,but now, u can find them with source code in my github [net.onebean.spring.boot](https://github.com/0nebean/net.onebean.spring.boot)
